services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: finspeed
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finspeed_dev
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://finspeed:password@db:5432/finspeed_dev?sslmode=disable
      - JWT_SECRET=dev-jwt-secret-key-change-in-production
      - FRONTEND_BASE_URL=http://localhost:3000
    depends_on:
      - db
    volumes:
      - ./api:/app
      - ./db:/app/db

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    user: "1000:1000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=/api/v1
      - API_PROXY_TARGET=http://api:8080
      - HOSTNAME=0.0.0.0
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: sh -c "pnpm install --frozen-lockfile && pnpm exec next dev -H 0.0.0.0 -p 3000"
    depends_on:
      - api

  admin-app:
    build:
      context: ./admin-app
      dockerfile: ../docker/admin.Dockerfile
    ports:
      - "3001:3001"
    user: "1000:1000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=/api/v1
      - NEXT_PUBLIC_ENABLE_M3=1
      - HOSTNAME=0.0.0.0
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
    depends_on:
      - api
    volumes:
      - ./admin-app:/app
    command: sh -c "pnpm config set store-dir /app/.pnpm-store && if [ ! -x node_modules/.bin/next ]; then pnpm install --no-optional; fi; pnpm exec next dev -H 0.0.0.0 -p 3001"

volumes:
  db_data:
  frontend_node_modules: