# Defines our local development environment, per task 1.11.
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: finspeed_dev
      POSTGRES_USER: finspeed
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
    depends_on:
      - db
    env_file:
      - ./api/.env.local

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api
    env_file:
      - ./frontend/.env.local

volumes:
  postgres_data:
    driver: local
