services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: finspeed
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finspeed_dev
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://finspeed:password@db:5432/finspeed_dev?sslmode=disable
      - JWT_SECRET=dev-jwt-secret-key-change-in-production
      - FRONTEND_BASE_URL=http://localhost:3000
    depends_on:
      - db
    volumes:
      - ./api:/app
      - ./db:/app/db

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=/api/v1
      - API_PROXY_TARGET=http://api:8080
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: pnpm dev
    depends_on:
      - api

volumes:
  db_data:
  frontend_node_modules: