variable "project_id" {}
variable "environment" {}
variable "region" {}
variable "zone" {}
variable "github_repository" {}
variable "database_tier" {}
variable "database_version" {}
variable "database_backup_enabled" {}
variable "database_backup_start_time" {}
variable "database_maintenance_window_day" {}
variable "database_maintenance_window_hour" {}
variable "api_cpu" {}
variable "api_memory" {}
variable "api_min_instances" {}
variable "api_max_instances" {}
variable "frontend_cpu" {}
variable "frontend_memory" {}
variable "frontend_min_instances" {}
variable "frontend_max_instances" {}
variable "domain_name" {}
variable "api_domain_name" {}
variable "enable_ssl" {}
variable "notification_email" {}
variable "enable_uptime_checks" {}
variable "enable_deletion_protection" {}
variable "labels" {}
variable "iap_support_email" {}
variable "iap_allowed_user" {}
variable "project_owner_email" {}

// Image variables (injected by CI during deploy)
variable "api_image" {}
variable "frontend_image" {}
variable "migrate_image" {}
