# Config file for air: https://github.com/cosmtrek/air

# Set an absolute path for the root inside the container
root = "/app"
tmp_dir = "tmp"

[build]
# Use absolute paths for the command and output
cmd = "go build -o ./tmp/server ./cmd/server"
# The binary that air will execute
bin = "./tmp/server"
# Files to watch
include_ext = ["go", "tpl", "tmpl", "html"]
# Directories to exclude from watching
exclude_dir = ["assets", "tmp", "vendor", "node_modules", ".git"]
log = "air.log"

[log]
time = true

[misc]
clean_on_exit = true
