# Production-Grade CI/CD Workflow for Production
# Deploys infrastructure and applications to the Finspeed production environment.

name: Deploy Production

on:
  push:
    branches:
      - main

# Environment variables available to all jobs
env:
  GCP_PROJECT_ID: finspeed-prod-st
  GCP_REGION: asia-south2
  GAR_LOCATION: asia-south2 # Google Artifact Registry location
  TF_STATE_BUCKET: finspeed-st-tf-state-prod
  API_IMAGE_NAME: finspeed-api-production
  FRONTEND_IMAGE_NAME: finspeed-frontend-production
  MIGRATE_IMAGE_NAME: finspeed-migrate-production

# Default permissions are read-only, reducing the attack surface.
permissions:
  contents: read

concurrency:
  group: deploy-production
  cancel-in-progress: false

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      api: ${{ steps.filter.outputs.api }}
      frontend: ${{ steps.filter.outputs.frontend }}
      infra: ${{ steps.filter.outputs.infra }}
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Detect changed paths
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            api:
              - 'api/**'
              - 'docker/api.Dockerfile'
              - 'docker/api.prod.Dockerfile'
              - 'docker/migrate.Dockerfile'
            frontend:
              - 'frontend/**'
              - 'docker/frontend.Dockerfile'
            infra:
              - 'infra/terraform/**'
              - '.github/workflows/deploy-production.yml'

  deploy-infra:
    name: Deploy Infrastructure
    if: github.event_name == 'push'
    needs: changes
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@b7593ed2efd1c1617e1b0254da33b86225adb2a5 # v2.1.12 # v2.1.2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_PROD }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_PROD }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

      - name: Cache Terraform plugins
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ env.TF_STATE_BUCKET }}"
        working-directory: ./infra/terraform/production

      - name: Terraform Apply Infra
        run: terraform apply -lock-timeout=5m -auto-approve -input=false
        working-directory: ./infra/terraform/production

      - name: Show Load Balancer IP
        run: |
          echo "Load Balancer IP (from Terraform output):"
          terraform output -raw load_balancer_ip || terraform output load_balancer_ip || true
        working-directory: ./infra/terraform/production

  build-and-push:
    name: Build and Push Images
    if: github.event_name == 'push' && (needs.changes.outputs.api == 'true' || needs.changes.outputs.frontend == 'true' || needs.changes.outputs.infra == 'true')
    needs: [changes, deploy-infra]
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write
      packages: write # Required for pushing to GAR
    outputs:
      image_tag: ${{ steps.image-metadata.outputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@b7593ed2efd1c1617e1b0254da33b86225adb2a5 # v2.1.2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_PROD }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_PROD }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.3.0

      - name: Generate Image Tag
        id: image-metadata
        run: echo "image_tag=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: Build and Push API Image
        if: needs.changes.outputs.api == 'true' || needs.changes.outputs.infra == 'true'
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          context: ${{ github.workspace }}
          file: ./docker/api.prod.Dockerfile
          push: true
          tags: |
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.API_IMAGE_NAME }}/${{ env.API_IMAGE_NAME }}:${{ steps.image-metadata.outputs.image_tag }}
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.API_IMAGE_NAME }}/${{ env.API_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push Frontend Image
        if: needs.changes.outputs.frontend == 'true' || needs.changes.outputs.infra == 'true'
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          context: ${{ github.workspace }}
          file: ./docker/frontend.Dockerfile
          target: prod
          push: true
          build-args: |
            NEXT_PUBLIC_ENVIRONMENT=production
          tags: |
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.FRONTEND_IMAGE_NAME }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ steps.image-metadata.outputs.image_tag }}
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.FRONTEND_IMAGE_NAME }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push Migrate Image
        if: needs.changes.outputs.api == 'true' || needs.changes.outputs.infra == 'true'
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          context: ${{ github.workspace }}
          file: ./docker/migrate.Dockerfile
          push: true
          tags: |
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.MIGRATE_IMAGE_NAME }}/${{ env.MIGRATE_IMAGE_NAME }}:${{ steps.image-metadata.outputs.image_tag }}
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.MIGRATE_IMAGE_NAME }}/${{ env.MIGRATE_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-services:
    name: Deploy Services
    if: github.event_name == 'push' && needs.build-and-push.outputs.image_tag != ''
    needs: [build-and-push, changes]
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@b7593ed2efd1c1617e1b0254da33b86225adb2a5 # v2.1.12
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_PROD }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_PROD }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

      - name: Cache Terraform plugins
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ env.TF_STATE_BUCKET }}"
        working-directory: ./infra/terraform/production

      - name: Set image variables from existing deployments or new builds
        shell: bash
        run: |
          set -euo pipefail
          # Set API image - use new build if API changed, otherwise get from existing deployment
          if [[ "${{ needs.changes.outputs.api }}" == "true" || "${{ needs.changes.outputs.infra }}" == "true" ]]; then
            echo "TF_VAR_api_image=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.API_IMAGE_NAME }}/${{ env.API_IMAGE_NAME }}:${{ needs.build-and-push.outputs.image_tag }}" >> $GITHUB_ENV
          else
            API_IMG=$(gcloud run services describe finspeed-api-production \
              --region=${{ env.GCP_REGION }} \
              --project=${{ env.GCP_PROJECT_ID }} \
              --format="value(spec.template.spec.containers[0].image)" 2>/dev/null || echo "")
            if [[ -n "${API_IMG}" ]]; then
              echo "TF_VAR_api_image=${API_IMG}" >> $GITHUB_ENV
            else
              echo "TF_VAR_api_image=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.API_IMAGE_NAME }}/${{ env.API_IMAGE_NAME }}:latest" >> $GITHUB_ENV
            fi
          fi

          # Set Frontend image - use new build if frontend changed, otherwise get from existing deployment
          if [[ "${{ needs.changes.outputs.frontend }}" == "true" || "${{ needs.changes.outputs.infra }}" == "true" ]]; then
            echo "TF_VAR_frontend_image=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.FRONTEND_IMAGE_NAME }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ needs.build-and-push.outputs.image_tag }}" >> $GITHUB_ENV
          else
            FRONTEND_IMG=$(gcloud run services describe finspeed-frontend-production \
              --region=${{ env.GCP_REGION }} \
              --project=${{ env.GCP_PROJECT_ID }} \
              --format="value(spec.template.spec.containers[0].image)" 2>/dev/null || echo "")
            if [[ -n "${FRONTEND_IMG}" ]]; then
              echo "TF_VAR_frontend_image=${FRONTEND_IMG}" >> $GITHUB_ENV
            else
              echo "TF_VAR_frontend_image=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.FRONTEND_IMAGE_NAME }}/${{ env.FRONTEND_IMAGE_NAME }}:latest" >> $GITHUB_ENV
            fi
          fi

          # Set Migrate image - use new build if API changed, otherwise get from existing deployment
          if [[ "${{ needs.changes.outputs.api }}" == "true" || "${{ needs.changes.outputs.infra }}" == "true" ]]; then
            echo "TF_VAR_migrate_image=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.MIGRATE_IMAGE_NAME }}/${{ env.MIGRATE_IMAGE_NAME }}:${{ needs.build-and-push.outputs.image_tag }}" >> $GITHUB_ENV
          else
            MIG_IMG=$(gcloud run jobs describe finspeed-migrate-production \
              --region=${{ env.GCP_REGION }} \
              --project=${{ env.GCP_PROJECT_ID }} \
              --format="value(spec.template.template.spec.containers[0].image)" 2>/dev/null || echo "")
            if [[ -z "${MIG_IMG}" ]]; then
              MIG_IMG=$(gcloud run jobs describe finspeed-migrate-production \
                --region=${{ env.GCP_REGION }} \
                --project=${{ env.GCP_PROJECT_ID }} \
                --format="value(spec.template.spec.containers[0].image)" 2>/dev/null || echo "")
            fi
            if [[ -n "${MIG_IMG}" && "${MIG_IMG}" != "null" ]]; then
              echo "TF_VAR_migrate_image=${MIG_IMG}" >> $GITHUB_ENV
            else
              echo "TF_VAR_migrate_image=us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0" >> $GITHUB_ENV
            fi
          fi
        working-directory: ./infra/terraform/production

      - name: Terraform Apply Service Images
        shell: bash
        run: |
          set -euo pipefail
          echo "Applying Terraform with:"
          echo "  api_image=${TF_VAR_api_image}"
          echo "  frontend_image=${TF_VAR_frontend_image}"
          echo "  migrate_image=${TF_VAR_migrate_image}"
          terraform apply -lock-timeout=5m -input=false -auto-approve \
            -var=api_image="${TF_VAR_api_image}" \
            -var=frontend_image="${TF_VAR_frontend_image}" \
            -var=migrate_image="${TF_VAR_migrate_image}"
          # Execute migrations when API or infra changed (new migrate image)
          if [[ "${{ needs.changes.outputs.api }}" == "true" || "${{ needs.changes.outputs.infra }}" == "true" ]]; then
            echo "Running database migrations job..."
            gcloud run jobs execute finspeed-migrate-production \
              --region=${{ env.GCP_REGION }} \
              --project=${{ env.GCP_PROJECT_ID }} \
              --wait
          else
            echo "Skipping migrations; no API/infra changes detected."
          fi
        working-directory: ./infra/terraform/production
